In [1]:
from lib.db_io import Engine

import pandas as pd
import numpy as np
from lib.utils import 구분데이터붙이기, 군집나누기

db_info = {'host': '34.42.230.14',
          'port': '5432',
          'db_name': 'postgres',
          'user_name': 'tgsociety',
          'password': 'tgsociety'}

st_dt = '2022-10-01 07:00:00+09'
ed_dt = '2025-12-19 23:00:00+09'

engine = Engine(db_info)


# wheres = []
# # wheres.append('"예약희망일시" >= \'{st_dt}\''.format(st_dt = st_dt))
# wheres.append('"예약희망일시" <= \'{ed_dt}\''.format(ed_dt = ed_dt))
data = engine.select(table = '고객수요', schema='datamart', columns = ['고객_접속일시', '예약희망일시', '예약희망_point', '고객_코드']
                     # , wheres = wheres
                     , orderbys = ['"예약희망일시" asc'], 
                                   gis_col = '예약희망_point' )
data

,고객_접속일시,예약희망일시,예약희망_point,고객_코드
0,2023-08-02 06:13:58+00:00,2023-09-01 00:00:00+00:00,POINT (127.11108 37.51482),35811
1,2023-08-06 05:09:52.646907+00:00,2023-09-01 00:00:00+00:00,POINT (127.02220 37.50288),5679
2,2023-08-31 03:55:41.126820+00:00,2023-09-01 01:00:00+00:00,POINT (126.98635 37.49838),35828
3,2023-08-30 02:54:04.568561+00:00,2023-09-01 01:30:00+00:00,POINT (127.02145 37.51381),5684
4,2023-08-31 04:18:41.578990+00:00,2023-09-01 01:30:00+00:00,POINT (127.10703 37.49867),35829
...,...,...,...,...
98564,2025-12-20 12:57:49.812070+00:00,2025-12-21 11:30:00+00:00,POINT (127.10659 37.50420),132750
98565,2025-11-24 18:08:08.013599+00:00,2025-12-21 12:00:00+00:00,POINT (127.10024 37.50128),132673
98566,2025-11-21 18:01:15.955874+00:00,2025-12-21 12:00:00+00:00,POINT (127.10524 37.50502),132657
98567,2025-12-13 03:15:45.525117+00:00,2025-12-21 12:00:00+00:00,POINT (127.08564 37.50976),132677
98568,2025-12-20 14:59:53.535469+00:00,2025-12-21 12:00:00+00:00,POINT (127.10560 37.47441),132759

In [2]:
from lib.검사 import 검증_unique
검증_unique(data = data, columns = ['고객_코드', '고객_접속일시'])

unique 조건 위반 record 수:  0

,고객_접속일시,예약희망일시,예약희망_point,고객_코드
0,2023-08-02 06:13:58+00:00,2023-09-01 00:00:00+00:00,POINT (127.11108 37.51482),35811
1,2023-08-06 05:09:52.646907+00:00,2023-09-01 00:00:00+00:00,POINT (127.02220 37.50288),5679
2,2023-08-31 03:55:41.126820+00:00,2023-09-01 01:00:00+00:00,POINT (126.98635 37.49838),35828
3,2023-08-30 02:54:04.568561+00:00,2023-09-01 01:30:00+00:00,POINT (127.02145 37.51381),5684
4,2023-08-31 04:18:41.578990+00:00,2023-09-01 01:30:00+00:00,POINT (127.10703 37.49867),35829
...,...,...,...,...
98564,2025-12-20 12:57:49.812070+00:00,2025-12-21 11:30:00+00:00,POINT (127.10659 37.50420),132750
98565,2025-11-24 18:08:08.013599+00:00,2025-12-21 12:00:00+00:00,POINT (127.10024 37.50128),132673
98566,2025-11-21 18:01:15.955874+00:00,2025-12-21 12:00:00+00:00,POINT (127.10524 37.50502),132657
98567,2025-12-13 03:15:45.525117+00:00,2025-12-21 12:00:00+00:00,POINT (127.08564 37.50976),132677
98568,2025-12-20 14:59:53.535469+00:00,2025-12-21 12:00:00+00:00,POINT (127.10560 37.47441),132759

In [3]:
from lib.검사 import 검증_notnull
검증_notnull(data = data, columns = ['고객_코드', '고객_접속일시'])

not null 조건 위반 record 수:  0

,고객_접속일시,예약희망일시,예약희망_point,고객_코드
0,2023-08-02 06:13:58+00:00,2023-09-01 00:00:00+00:00,POINT (127.11108 37.51482),35811
1,2023-08-06 05:09:52.646907+00:00,2023-09-01 00:00:00+00:00,POINT (127.02220 37.50288),5679
2,2023-08-31 03:55:41.126820+00:00,2023-09-01 01:00:00+00:00,POINT (126.98635 37.49838),35828
3,2023-08-30 02:54:04.568561+00:00,2023-09-01 01:30:00+00:00,POINT (127.02145 37.51381),5684
4,2023-08-31 04:18:41.578990+00:00,2023-09-01 01:30:00+00:00,POINT (127.10703 37.49867),35829
...,...,...,...,...
98564,2025-12-20 12:57:49.812070+00:00,2025-12-21 11:30:00+00:00,POINT (127.10659 37.50420),132750
98565,2025-11-24 18:08:08.013599+00:00,2025-12-21 12:00:00+00:00,POINT (127.10024 37.50128),132673
98566,2025-11-21 18:01:15.955874+00:00,2025-12-21 12:00:00+00:00,POINT (127.10524 37.50502),132657
98567,2025-12-13 03:15:45.525117+00:00,2025-12-21 12:00:00+00:00,POINT (127.08564 37.50976),132677
98568,2025-12-20 14:59:53.535469+00:00,2025-12-21 12:00:00+00:00,POINT (127.10560 37.47441),132759

In [4]:
from lib.검사 import 레코드수
레코드수(data = data, columns = ['고객_코드', '고객_접속일시'])

unique 조건 위반 record 수:  0
not null 조건 위반 record 수:  0

98569