In [1]:
from lib.db_io import Engine

import pandas as pd
import numpy as np
from lib.utils import 구분데이터붙이기, 군집나누기
from lib.simulator_03 import Simulator_01
from scipy.stats import ks_2samp
import warnings
warnings.filterwarnings(action='ignore')

db_info = {'host': '34.42.230.14',
          'port': '5432',
          'db_name': 'postgres',
          'user_name': 'tgsociety',
          'password': 'tgsociety'}

st_dt = '2025-01-01 07:00:00+09'
ed_dt = '2025-12-19 23:00:00+09'
시군구_ids = ['11220'
           # , '11230', '11240'
          ]

engine = Engine(db_info)


wheres = []
wheres.append('"예약희망일시" >= \'{st_dt}\''.format(st_dt = st_dt))
wheres.append('"예약희망일시" <= \'{ed_dt}\''.format(ed_dt = ed_dt))
wheres.append('"시군구_id" in (\'{}\')'.format(시군구_ids[0] # (\'{}\', \'{}\', \'{}\')
                                                            # , 시군구_ids[1], 시군구_ids[2]
                                                           )
             )
실제데이터 = engine.select(table = '고객수요_집계구_뷰'
                           , schema = 'datamart'
                           , columns = ['시군구_id', '고객_접속일시', '예약희망일시', '예약희망_point']
                           , wheres = wheres
                           , orderbys = ['"예약희망일시" asc']
                           , gis_col = '예약희망_point' )
실제데이터

,시군구_id,고객_접속일시,예약희망일시,예약희망_point
0,11220,2024-12-31 01:51:58.582332+00:00,2025-01-01 00:30:00+00:00,POINT (127.04351 37.47555)
1,11220,2024-12-31 01:51:58.582332+00:00,2025-01-01 00:30:00+00:00,POINT (127.04351 37.47555)
2,11220,2024-12-02 04:20:00.359318+00:00,2025-01-01 02:00:00+00:00,POINT (127.02724 37.49371)
3,11220,2024-12-31 05:58:09.384921+00:00,2025-01-01 03:30:00+00:00,POINT (127.03037 37.49053)
4,11220,2024-12-31 08:29:57.278392+00:00,2025-01-01 05:30:00+00:00,POINT (127.01252 37.48710)
...,...,...,...,...
7009,11220,2025-12-18 11:59:56.783446+00:00,2025-12-19 09:00:00+00:00,POINT (127.04237 37.47412)
7010,11220,2025-12-18 12:28:37.850481+00:00,2025-12-19 09:30:00+00:00,POINT (127.02206 37.49974)
7011,11220,2025-12-18 12:28:57.985291+00:00,2025-12-19 09:30:00+00:00,POINT (127.01280 37.50094)
7012,11220,2025-12-18 14:29:50.075931+00:00,2025-12-19 11:30:00+00:00,POINT (126.98972 37.49133)
7013,11220,2025-12-18 14:29:50.075931+00:00,2025-12-19 11:30:00+00:00,POINT (126.98972 37.49133)

In [2]:
import time
cur_datas = []
for try_num in range(3):
    st = time.time()
    simulator = Simulator_01(
                                 simulation_start_dt = st_dt, 
                                 simulation_end_dt = ed_dt,
        data_start_date = st_dt,
                                 data_end_date = ed_dt,
                                 db_info = db_info,
                                 is_first = True,
                                시군구_ids = ['11220'
                                           # , '11230', '11240'
                                          ], 차량숫자 = 4, # 4 or 15
    try_num = try_num)
    cur_datas.append(구분데이터붙이기(simulator.가예약정보.copy(), '예약희망일시'))
    print('try 종료 ({})'.format(time.time()-st))

try 종료 (49.87983322143555)
try 종료 (49.37773323059082)
try 종료 (50.166165828704834)

In [3]:
cur_datas[0]

,고객_접속일시,예약희망일시,예약희망_point,월,요일,공휴일,시간대,접속연월일,연월일,연
0,2024-12-31 11:56:25.630649+09:00,2025-01-01 09:00:00+09:00,None,01,2,True,조조,20241231,20250101,2025
1,2024-12-20 10:52:05.476427+09:00,2025-01-01 09:30:00+09:00,None,01,2,True,조조,20241220,20250101,2025
2,2024-12-31 13:59:54.526115+09:00,2025-01-01 11:00:00+09:00,None,01,2,True,점심,20241231,20250101,2025
3,2024-12-31 14:28:48.539661+09:00,2025-01-01 11:30:00+09:00,None,01,2,True,점심,20241231,20250101,2025
4,2024-12-02 21:59:58.541732+09:00,2025-01-01 11:30:00+09:00,None,01,2,True,점심,20241202,20250101,2025
...,...,...,...,...,...,...,...,...,...,...
7356,2025-12-18 17:53:18.892923+09:00,2025-12-19 20:30:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7357,2025-12-18 23:29:53.290654+09:00,2025-12-19 20:30:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7358,2025-11-19 23:15:39.621749+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251119,20251219,2025
7359,2025-12-17 20:02:31.144767+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251217,20251219,2025
7360,2025-12-18 23:58:47.174109+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025

In [4]:
cur_datas[1]

,고객_접속일시,예약희망일시,예약희망_point,월,요일,공휴일,시간대,접속연월일,연월일,연
0,2024-12-31 12:27:06.757889+09:00,2025-01-01 09:30:00+09:00,None,01,2,True,조조,20241231,20250101,2025
1,2024-12-31 12:21:12.658351+09:00,2025-01-01 09:30:00+09:00,None,01,2,True,조조,20241231,20250101,2025
2,2024-12-31 13:59:56.399147+09:00,2025-01-01 11:00:00+09:00,None,01,2,True,점심,20241231,20250101,2025
3,2024-12-31 13:58:50.275221+09:00,2025-01-01 11:00:00+09:00,None,01,2,True,점심,20241231,20250101,2025
4,2024-12-31 14:29:38.597231+09:00,2025-01-01 11:30:00+09:00,None,01,2,True,점심,20241231,20250101,2025
...,...,...,...,...,...,...,...,...,...,...
7172,2025-11-19 19:09:11.746093+09:00,2025-12-19 18:00:00+09:00,None,12,4,False,저녁,20251119,20251219,2025
7173,2025-12-18 22:47:31.507419+09:00,2025-12-19 20:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7174,2025-12-18 23:27:42.776570+09:00,2025-12-19 20:30:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7175,2025-12-18 23:29:57.316771+09:00,2025-12-19 20:30:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7176,2025-12-18 21:19:54.969225+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025

In [5]:
cur_datas[2]

,고객_접속일시,예약희망일시,예약희망_point,월,요일,공휴일,시간대,접속연월일,연월일,연
0,2024-12-02 22:17:19.250000+09:00,2025-01-01 09:00:00+09:00,None,01,2,True,조조,20241202,20250101,2025
1,2024-12-31 12:18:18.516740+09:00,2025-01-01 09:30:00+09:00,None,01,2,True,조조,20241231,20250101,2025
2,2024-12-30 20:00:13.797890+09:00,2025-01-01 10:00:00+09:00,None,01,2,True,점심,20241230,20250101,2025
3,2024-12-31 12:12:05.267830+09:00,2025-01-01 11:00:00+09:00,None,01,2,True,점심,20241231,20250101,2025
4,2024-12-31 12:26:43.407110+09:00,2025-01-01 11:00:00+09:00,None,01,2,True,점심,20241231,20250101,2025
...,...,...,...,...,...,...,...,...,...,...
7281,2025-12-18 20:53:07.384061+09:00,2025-12-19 18:30:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7282,2025-12-18 21:57:02.732745+09:00,2025-12-19 19:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7283,2025-11-19 21:17:50.712775+09:00,2025-12-19 20:30:00+09:00,None,12,4,False,저녁,20251119,20251219,2025
7284,2025-12-18 23:56:32.680502+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025
7285,2025-12-18 23:58:25.915982+09:00,2025-12-19 21:00:00+09:00,None,12,4,False,저녁,20251218,20251219,2025

In [6]:
ref_data = 구분데이터붙이기(실제데이터.copy(), '예약희망일시')
ref_data['date'] = ref_data['예약희망일시'].dt.date
for i in range(3):
    cur_data = cur_datas[i].copy()
    cur_data['date'] = cur_data['예약희망일시'].dt.date
    ref_counts_list = ref_data['date'].value_counts().sort_index().tolist()
    cur_counts_list = cur_data['date'].value_counts().sort_index().tolist()
    print(ks_2samp(ref_counts_list, cur_counts_list)[1].item())

0.6867689062883032
0.9871153523037283
0.5605829973691095